name: Android Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android (Debug)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build Android (Debug)
        uses: croconut/godot-multi-builder@v1
        id: build_android
        with:
          names: "Android"
          debug-mode: "true"
          
      - name: Unzip Build
        run: |
          unzip builds/builds.zip -d builds/android
          
      - name: Upload Android Build
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-build
          path: builds/android/
          retention-days: 14

      - name: Upload Build Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-build-log
          path: ${{ steps.build_android.outputs.build_logs }}
          retention-days: 3