name: Android Build
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  android-build:
    name: Android Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/* ~/.local/share/godot/export_templates/
      
      - name: Android Build
        run: |
          mkdir -p build/android
          godot --headless --verbose --export-release "Android" build/android/game.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: build/android/game.apk