name: Android Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android (Debug)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build Android (Debug)
        uses: dulvui/godot-android-export@v4
        with:
          godot-version: 4.2.2
          working-directory: .
          
      - name: Upload Android Build
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-build
          path: android/build/
          retention-days: 14