name: "Godot CI/CD"

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: ${{ github.event.repository.name }}
  PROJECT_PATH: ${{ secrets.PROJECT_PATH }}

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd ${PROJECT_PATH}
          godot --headless --verbose --export-release "Web" build/web/index.html
      - name: Create Headers
        run: |
          echo "/*" > build/web/_headers
          echo "  Cross-Origin-Embedder-Policy: require-corp" >> build/web/_headers
          echo "  Cross-Origin-Opener-Policy: same-origin" >> build/web/_headers
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
          clean: true
          commit-message: "ci: Deploy GitHub Page | ${{ env.EXPORT_NAME }}:${{ github.job }}"
