name: "Godot CI/CD"

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
      options: --user root
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir -p build/web
          godot --headless --verbose --export-release "Web" build/web/index.html || exit 1

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
