name: Linux Build

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Setup Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/* ~/.local/share/godot/export_templates/
      
      - name: Cache Godot files
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/godot/
            ~/.cache/godot/
          key: ${{ runner.os }}-godot-${{ hashFiles('**/*.tscn', '**/*.gd') }}
          restore-keys: |
            ${{ runner.os }}-godot-
      
      - name: Build
        run: |
          mkdir -p build/linux
          godot --headless --verbose --export-release "Linux/X11" build/linux/game.x86_64
          
      - name: Create Linux Archive
        run: |
          cd build/linux
          zip -r game-linux.zip game.x86_64
          
      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux/game-linux.zip
          retention-days: 7