name: Web Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Setup Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/* ~/.local/share/godot/export_templates/
      
      - name: Debug Export Presets
        run: |
          ls -la
          cat export_presets.cfg || echo "export_presets.cfg not found!"
      
      - name: Cache Godot files
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/godot/
            ~/.cache/godot/
          key: ${{ runner.os }}-godot-${{ hashFiles('**/*.tscn', '**/*.gd') }}
          restore-keys: |
            ${{ runner.os }}-godot-
      
      - name: Build
        run: |
          mkdir -p build/web
          godot --headless --verbose --export-release "Web" build/web/index.html
          
      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
          retention-days: 7