name: Windows Build

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    name: Build Windows
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Setup Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/* ~/.local/share/godot/export_templates/
      
      - name: Cache Godot files
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/godot/
            ~/.cache/godot/
          key: ${{ runner.os }}-godot-${{ hashFiles('**/*.tscn', '**/*.gd') }}
          restore-keys: |
            ${{ runner.os }}-godot-
      
      - name: Build
        run: |
          mkdir -p build/windows
          godot --headless --verbose --export-release "Windows Desktop" build/windows/game.exe
          cd build/windows
          zip -r game-windows.zip game.exe
          
      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/game-windows.zip
          retention-days: 7